### ISSUE TITLE
Problem saving a new car

### ISSUE THREAD

**Issue by jeanminet** [sdenel/lightHTTPLocalStorage#1]
After a new car is saved, `garage.json` is updated but the application does not know it.

**Comment by sdenel** [comment]
I cannot reproduce the bug, but I just committed a minor edit which could change the described behavior. Could you please confirm the persistence of the bug?

**Comment by jeanminet** [comment]
The problem only appears with IE as a browser.
I changed my defaul browser to Firefox and it is working well.
It is also working on Ubuntu with Firefox.
